sonar.projectKey=Valyo96_wealth-stack
sonar.organization=valyo96

sonar.projectName=wealth-stack
sonar.projectVersion=0.1.0

sonar.sources=backend,web/src
sonar.tests=backend,web/src
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.test.tsx

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,backend/internal/store/**,web/src/test/**

sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info

sonar.sourceEncoding=UTF-8
